runtime: java

env: flex

handlers:
  - url: /.*
    script: this field is required, but ignored
# Application Resources
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5
# Automatic Scaling
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4